services:
  - type: web
    name: betterbt
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: OUTLOOK_USERS
        sync: false
      - key: BIGTIME_API_TOKEN
        sync: false
      - key: BIGTIME_FIRM_ID
        sync: false
